services:
  immich-poller:
    image: ion606/immich-webhook-poller:latest
    env_file: .env

    # if you want persistance
    volumes:
      - immich_hooks_data:/data

# if you want persistance
volumes:
  immich_hooks_data:
