services:
  immich-poller:
    image: ion606/immich-webhook-poller:latest
    env_file: .env

    # if you want persistance
    volumes:
      - ./hooks.json:/hooks.json
      - ./store.txt:/data/store.txt

# if you want persistance
volumes:
  immich_hooks_data:
